# https://github.com/koddr/example-static-website-docker-nginx-certbot/blob/master/docker-compose.ymls

version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - nginx_net
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:172.17.0.1
    volumes:
      - ~/.docker/certbot/conf:/etc/letsencrypt
      - ~/.docker/certbot/www:/var/www/certbot
      - ~/.docker/certbot/dhparam.pem:/etc/ssl/dhparam.pem
      - ~/.docker/certbot/log:/var/log/letsencrypt
      - ./nginx/logs:/etc/nginx/logs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/sites-enabled/certbot.conf:/etc/nginx/sites-enabled/certbot.conf
      - ./nginx/sites-enabled/api.mirigana.app.conf:/etc/nginx/sites-enabled/api.mirigana.app.conf
